services:
  - type: web
    name: perfscanimal-health-backend
    runtime: python310
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyAVLDoBy3gs48NtoGjsZzt_c56cXbw-b40
      - key: PYTHON_VERSION
        value: '3.10'
